Add (broken) explore subcommands.

diff --git a/fdfd b/fdfd
--- a/fdfd
+++ b/fdfd
@@ -10,6 +10,64 @@ cleanup() { if [ -v tmp ]; then @coreutils@/bin/rm -rf "$tmp"; fi }
 trap cleanup EXIT
 tmp=$(@coreutils@/bin/mktemp --directory --tmpdir "$me".XXXXXXXX)
 
+command_explorable() {
+    if [ $# -ne 1 ]; then exit_usage "explorable DBDIR"; fi
+    command_query "$1" '
+        SELECT ?url
+        WHERE {
+            ?url amfd:review/amfd:worth-posting true .
+            FILTER NOT EXISTS { ?explore amfd:explore-url ?url }
+        }
+        ' |
+    @jq@/bin/jq -r '.results.bindings | .[] | .url.value'
+}
+
+command_explore() {
+    local url exploredir now extracted wgetexit s3base s3dir workdir
+    if [ $# -lt 1 ]; then exit_usage "explore S3BASE [URL ...]"; fi
+    s3base=$1
+    shift
+    workdir=$(subtmpdir)
+    for url in "$@"; do
+        @coreutils@/bin/rm -rf "$workdir"/explore
+        @coreutils@/bin/mkdir "$workdir"/explore
+        s3dir=$(s3_stash_dir "$url")
+        preamble_turtle
+        echo "@base <$s3base/$s3dir/> ."
+        echo "<.> rdf:type amfd:explore ;"
+        echo "  amfd:explore-url <$url> ;"
+        now=$(timestamp)
+        echo "  amfd:when-start $now ."
+        set +e
+        @wget@/bin/wget \
+            --output-file="$workdir"/explore/wget.log \
+            --force-directories \
+            --directory-prefix="$workdir"/explore \
+            --adjust-extension \
+            --recursive \
+            --level=2 \
+            --span-hosts \
+            "$url"
+        wgetexit=$?
+        set -e
+        case "$wgetexit" in
+            0)  @findutils@/bin/find \
+                    "$workdir"/explore \
+                    -type f \
+                    -iregex '.*\.html?$' \
+                    -print0 |
+                @findutils@/bin/xargs -0 "$here"/extract-feed |
+                @sed@/bin/sed 's,.*,<&> a amfd:feed .,'
+                ;;
+            *)  echo "<.> amfd:error \"wget-${wgetexit}\" ."
+                ;;
+        esac
+        stash "$workdir"/explore "$s3base/$s3dir" >&2
+        now=$(timestamp)
+        echo "<.> amfd:when-end $now ."
+    done
+}
+
 command_feed() {
     if [ $# -gt 0 ]; then preamble_turtle; fi
     for url in "$@"; do
