fetch: Recover from errors in individual feeds.

diff --git a/fetch b/fetch
--- a/fetch
+++ b/fetch
@@ -38,5 +38,8 @@ tofetch=$(echo "$newrate" |@awk@/bin/awk '{ print int($0+0.5) }')
 
 @coreutils@/bin/sort -R "$tmp"/fetchable |
 @sed@/bin/sed -n "1,${tofetch}p" |
-@findutils@/bin/xargs "$here"/fdfd fetch |
-@findutils@/bin/xargs "$here"/fdfd merge "$dbdir"
+while read url; do
+  if ! "$here"/fdfd fetch "$url" | "$here"/fdfd merge "$dbdir"; then
+    echo "$me: error fetching & merging $url" >&2
+  fi
+done
